package MyDsl.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private final ConceptPresentation props_Controller = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Endpoint = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_RestApi = new ConceptPresentationBuilder().shortDesc("A collection of Spring controllers for the described REST API.").create();

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.Controller:
        return props_Controller;
      case LanguageConceptSwitch.Endpoint:
        return props_Endpoint;
      case LanguageConceptSwitch.RestApi:
        return props_RestApi;
    }
    return null;
  }
}
