package MyDsl.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Controller = 0;
  public static final int Endpoint = 1;
  public static final int RestApi = 2;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xe996750bbfdf408eL, 0x8fdfe6b6f722115cL);
    builder.put(0x77c6db53f6026c2bL, Controller);
    builder.put(0x77c6db53f60312f0L, Endpoint);
    builder.put(0x77c6db53f6026c22L, RestApi);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
